version: 2
jobs:
  test_make:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: 
          name: Install dependency
          command: |
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            pip install --user -r requirements.txt
      - run: sphinx-build . _build -w sphinx-doctest.warnings.log
      - run: cat sphinx-doctest.warnings.log
      - run: grep -q "ERROR:" sphinx-doctest.warnings.log || exit 1
      - run: grep -q "WARNING:" sphinx-doctest.warnings.log || exit 1
      - store_artifacts:
          path: sphinx-doctest.warnings.log
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_make
